### PR TITLE
[1.x] Switch to platform options from deprecated custom schema options

### PR DESCRIPTION
**Pull request by thomas-dion-113**
Apply changes for branch 1.x (same as #64)

### CODE REVIEW

**Comment by maxhelias** [comment]
The maintenance effort for this version, which is already way behind, isn't worth it for this one fix.
Upgrading to version 2 doesn't seem complicated.

**Comment by thomas-dion-113** [comment]
> The maintenance effort for this version, which is already way behind, isn't worth it for this one fix. Upgrading to version 2 doesn't seem complicated.

Upgrading to version 2 seems complicated for projects that still use php7 because it requires php8.

**Comment by maxhelias** [comment]
@thomas-dion-113 No, because requiring version 8 of php will not update the next release in your project.

**Comment by thomas-dion-113** [comment]
Sorry but I don't understand, do you mean version 2 works with php7 ? 

Version 1:
https://github.com/jsor/doctrine-postgis/blob/638aac2e317c8aeae6f32297a2288ae8a46c60e4/composer.json#L25

Version 2:
https://github.com/jsor/doctrine-postgis/blob/8690f4ce7a371686634d3bfe40178f668005ab5a/composer.json#L25

**Comment by maxhelias** [comment]
@thomas-dion-113 This depreciation has already been corrected in version 2, so upgrade your application to PHP 8 and, after the upgrade, update this package.
Version 1 has been inactive for almost 2 years.

**Pull request closed without merging**
